version: "0.5"

nodes:
  build:
    matrix:
      dense:
        dimensions:
          - - env:
                RELEASE: ""
            - env:
                RELEASE: "--release"
          - - env:
                FEATURES: "--no-default-features"
            - env:
                FEATURES: ""
            - env:
                FEATURES: "--features=backend+cli"
    tasks:
      - script: |
          set -e
          cargo build $FEATURES $RELEASE

  "test:regression":
    env:
      vars:
        config: "./test/.complate/config.yaml"
    tasks:
      - script: |
          set -e
          export RUST_BACKTRACE=1
          cargo test

  "hook:pre-push":
    pre:
      - build
      - "test:regression"
    tasks: []
