apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.env }}-nginx
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{ .Values.env }}-nginx
