name: pipeline
on: push

jobs:
  check:
    name: check (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: "default"
          features: ""
        - name: "all"
          features: --all-features
        - name: "backend+ui"
          features: --features "backend+ui" --no-default-features
    steps:
    - uses: actions/checkout@v1
    - name: install tools
      run: sudo apt-get install build-essential libncurses5-dev libncursesw5-dev
    - name: execute unit tests
      run: cargo test ${{ matrix.features }}
    - name: build program
      run: cargo build ${{ matrix.features }}
    - name: run cli tests
      working-directory: test
      run: sh test-cli.sh
